# coding=iso-8859-15
"""
This list contains the country names (official short names in English) in 
alphabetical order as given in ISO 3166-1 and the corresponding 
ISO 3166-1-alpha-2 code elements. """

countries = (
    ("af", u"Afghanistan"),
    ("ax", u"Aland Islands"),
    ("al", u"Albania"),
    ("dz", u"Algeria"),
    ("as", u"American Samoa"),
    ("ad", u"Andorra"),
    ("ao", u"Angola"),
    ("ai", u"Anguilla"),
    ("aq", u"Antarctica"),
    ("ag", u"Antigua And Barbuda"),
    ("ar", u"Argentina"),
    ("am", u"Armenia"),
    ("aw", u"Aruba"),
    ("au", u"Australia"),
    ("at", u"Austria"),
    ("az", u"Azerbaijan"),
    ("bs", u"Bahamas"),
    ("bh", u"Bahrain"),
    ("bd", u"Bangladesh"),
    ("bb", u"Barbados"),
    ("by", u"Belarus"),
    ("be", u"Belgium"),
    ("bz", u"Belize"),
    ("bj", u"Benin"),
    ("bm", u"Bermuda"),
    ("bt", u"Bhutan"),
    ("bo", u"Bolivia"),
    ("ba", u"Bosnia And Herzegovina"),
    ("bw", u"Botswana"),
    ("bv", u"Bouvet Island"),
    ("br", u"Brazil"),
    ("io", u"British Indian Ocean Territory"),
    ("bn", u"Brunei Darussalam"),
    ("bg", u"Bulgaria"),
    ("bf", u"Burkina Faso"),
    ("bi", u"Burundi"),
    ("kh", u"Cambodia"),
    ("cm", u"Cameroon"),
    ("ca", u"Canada"),
    ("cv", u"Cape Verde"),
    ("ky", u"Cayman Islands"),
    ("cf", u"Central African Republic"),
    ("td", u"Chad"),
    ("cl", u"Chile"),
    ("cn", u"China"),
    ("cx", u"Christmas Island"),
    ("cc", u"Cocos (Keeling) Islands"),
    ("co", u"Colombia"),
    ("km", u"Comoros"),
    ("cg", u"Congo"),
    ("cd", u"Congo, The Democratic Republic Of The"),
    ("ck", u"Cook Islands"),
    ("cr", u"Costa Rica"),
    ("ci", u"CÔTe D'Ivoire"),
    ("hr", u"Croatia"),
    ("cu", u"Cuba"),
    ("cy", u"Cyprus"),
    ("cz", u"Czech Republic"),
    ("dk", u"Denmark"),
    ("dj", u"Djibouti"),
    ("dm", u"Dominica"),
    ("do", u"Dominican Republic"),
    ("ec", u"Ecuador"),
    ("eg", u"Egypt"),
    ("sv", u"El Salvador"),
    ("gq", u"Equatorial Guinea"),
    ("er", u"Eritrea"),
    ("ee", u"Estonia"),
    ("et", u"Ethiopia"),
    ("fk", u"Falkland Islands (Malvinas)"),
    ("fo", u"Faroe Islands"),
    ("fj", u"Fiji"),
    ("fi", u"Finland"),
    ("fr", u"France"),
    ("gf", u"French Guiana"),
    ("pf", u"French Polynesia"),
    ("tf", u"French Southern Territories"),
    ("ga", u"Gabon"),
    ("gm", u"Gambia"),
    ("ge", u"Georgia"),
    ("de", u"Germany"),
    ("gh", u"Ghana"),
    ("gi", u"Gibraltar"),
    ("gr", u"Greece"),
    ("gl", u"Greenland"),
    ("gd", u"Grenada"),
    ("gp", u"Guadeloupe"),
    ("gu", u"Guam"),
    ("gt", u"Guatemala"),
    ("gg", u"Guernsey"),
    ("gn", u"Guinea"),
    ("gw", u"Guinea-Bissau"),
    ("gy", u"Guyana"),
    ("ht", u"Haiti"),
    ("hm", u"Heard Island And Mcdonald Islands"),
    ("va", u"Holy See (Vatican City State)"),
    ("hn", u"Honduras"),
    ("hk", u"Hong Kong"),
    ("hu", u"Hungary"),
    ("is", u"Iceland"),
    ("in", u"India"),
    ("id", u"Indonesia"),
    ("ir", u"Iran, Islamic Republic Of"),
    ("iq", u"Iraq"),
    ("ie", u"Ireland"),
    ("im", u"Isle Of Man"),
    ("il", u"Israel"),
    ("it", u"Italy"),
    ("jm", u"Jamaica"),
    ("jp", u"Japan"),
    ("je", u"Jersey"),
    ("jo", u"Jordan"),
    ("kz", u"Kazakhstan"),
    ("ke", u"Kenya"),
    ("ki", u"Kiribati"),
    ("kp", u"Korea, Democratic People'S Republic Of"),
    ("kr", u"Korea, Republic Of"),
    ("kw", u"Kuwait"),
    ("kg", u"Kyrgyzstan"),
    ("la", u"Lao People'S Democratic Republic"),
    ("lv", u"Latvia"),
    ("lb", u"Lebanon"),
    ("ls", u"Lesotho"),
    ("lr", u"Liberia"),
    ("ly", u"Libyan Arab Jamahiriya"),
    ("li", u"Liechtenstein"),
    ("lt", u"Lithuania"),
    ("lu", u"Luxembourg"),
    ("mo", u"Macao"),
    ("mk", u"Macedonia, The Former Yugoslav Republic Of"),
    ("mg", u"Madagascar"),
    ("mw", u"Malawi"),
    ("my", u"Malaysia"),
    ("mv", u"Maldives"),
    ("ml", u"Mali"),
    ("mt", u"Malta"),
    ("mh", u"Marshall Islands"),
    ("mq", u"Martinique"),
    ("mr", u"Mauritania"),
    ("mu", u"Mauritius"),
    ("yt", u"Mayotte"),
    ("mx", u"Mexico"),
    ("fm", u"Micronesia, Federated States Of"),
    ("md", u"Moldova, Republic Of"),
    ("mc", u"Monaco"),
    ("mn", u"Mongolia"),
    ("me", u"Montenegro"),
    ("ms", u"Montserrat"),
    ("ma", u"Morocco"),
    ("mz", u"Mozambique"),
    ("mm", u"Myanmar"),
    ("na", u"Namibia"),
    ("nr", u"Nauru"),
    ("np", u"Nepal"),
    ("nl", u"Netherlands"),
    ("an", u"Netherlands Antilles"),
    ("nc", u"New Caledonia"),
    ("nz", u"New Zealand"),
    ("ni", u"Nicaragua"),
    ("ne", u"Niger"),
    ("ng", u"Nigeria"),
    ("nu", u"Niue"),
    ("nf", u"Norfolk Island"),
    ("mp", u"Northern Mariana Islands"),
    ("no", u"Norway"),
    ("om", u"Oman"),
    ("pk", u"Pakistan"),
    ("pw", u"Palau"),
    ("ps", u"Palestinian Territory, Occupied"),
    ("pa", u"Panama"),
    ("pg", u"Papua New Guinea"),
    ("py", u"Paraguay"),
    ("pe", u"Peru"),
    ("ph", u"Philippines"),
    ("pn", u"Pitcairn"),
    ("pl", u"Poland"),
    ("pt", u"Portugal"),
    ("pr", u"Puerto Rico"),
    ("qa", u"Qatar"),
    ("re", u"RÉUnion"),
    ("ro", u"Romania"),
    ("ru", u"Russian Federation"),
    ("rw", u"Rwanda"),
    ("bl", u"Saint BarthÉLemy"),
    ("sh", u"Saint Helena"),
    ("kn", u"Saint Kitts And Nevis"),
    ("lc", u"Saint Lucia"),
    ("mf", u"Saint Martin"),
    ("pm", u"Saint Pierre And Miquelon"),
    ("vc", u"Saint Vincent And The Grenadines"),
    ("ws", u"Samoa"),
    ("sm", u"San Marino"),
    ("st", u"Sao Tome And Principe"),
    ("sa", u"Saudi Arabia"),
    ("sn", u"Senegal"),
    ("rs", u"Serbia"),
    ("sc", u"Seychelles"),
    ("sl", u"Sierra Leone"),
    ("sg", u"Singapore"),
    ("sk", u"Slovakia"),
    ("si", u"Slovenia"),
    ("sb", u"Solomon Islands"),
    ("so", u"Somalia"),
    ("za", u"South Africa"),
    ("gs", u"South Georgia And The South Sandwich Islands"),
    ("es", u"Spain"),
    ("lk", u"Sri Lanka"),
    ("sd", u"Sudan"),
    ("sr", u"Suriname"),
    ("sj", u"Svalbard And Jan Mayen"),
    ("sz", u"Swaziland"),
    ("se", u"Sweden"),
    ("ch", u"Switzerland"),
    ("sy", u"Syrian Arab Republic"),
    ("tw", u"Taiwan, Province Of China"),
    ("tj", u"Tajikistan"),
    ("tz", u"Tanzania, United Republic Of"),
    ("th", u"Thailand"),
    ("tl", u"Timor-Leste"),
    ("tg", u"Togo"),
    ("tk", u"Tokelau"),
    ("to", u"Tonga"),
    ("tt", u"Trinidad And Tobago"),
    ("tn", u"Tunisia"),
    ("tr", u"Turkey"),
    ("tm", u"Turkmenistan"),
    ("tc", u"Turks And Caicos Islands"),
    ("tv", u"Tuvalu"),
    ("ug", u"Uganda"),
    ("ua", u"Ukraine"),
    ("ae", u"United Arab Emirates"),
    ("gb", u"United Kingdom"),
    ("us", u"United States"),
    ("um", u"United States Minor Outlying Islands"),
    ("uy", u"Uruguay"),
    ("uz", u"Uzbekistan"),
    ("vu", u"Vanuatu"),
    ("ve", u"Venezuela"),
    ("vn", u"Viet Nam"),
    ("vg", u"Virgin Islands, British"),
    ("vi", u"Virgin Islands, U.S."),
    ("wf", u"Wallis And Futuna"),
    ("eh", u"Western Sahara"),
    ("ye", u"Yemen"),
    ("zm", u"Zambia"),
    ("zw", u"Zimbabwe")
)